version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    environment:
      - FIREBASE_CREDENTIALS=./credentials/firebaseAdminCredentials.json
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: process.env.BDDpsw
      MYSQL_DATABASE: process.env.BDDdatabase
