// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDefSTLqQqLAFES07_ryq72LcqnW_BOOZk',
    appId: '1:741858065565:web:0acb7fa85536371222a874',
    messagingSenderId: '741858065565',
    projectId: 'social-co2',
    authDomain: 'social-co2.firebaseapp.com',
    storageBucket: 'social-co2.appspot.com',
    measurementId: 'G-R6FKPYYPGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1UAFvblz_8xylYI911ktu4aGV8qEz1MU',
    appId: '1:741858065565:android:4a92fbb0e0846d4f22a874',
    messagingSenderId: '741858065565',
    projectId: 'social-co2',
    storageBucket: 'social-co2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjkr9CwboejhcbKb7dg9lyhiui_7txhMY',
    appId: '1:741858065565:ios:d141507cc7090df622a874',
    messagingSenderId: '741858065565',
    projectId: 'social-co2',
    storageBucket: 'social-co2.appspot.com',
    androidClientId: '741858065565-17f32upi8c40crbi1bg68e5v7au24sbo.apps.googleusercontent.com',
    iosClientId: '741858065565-nr3mk7l8t7asrmh06ljf6iuoe3aj0r67.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialCo2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjkr9CwboejhcbKb7dg9lyhiui_7txhMY',
    appId: '1:741858065565:ios:d141507cc7090df622a874',
    messagingSenderId: '741858065565',
    projectId: 'social-co2',
    storageBucket: 'social-co2.appspot.com',
    androidClientId: '741858065565-17f32upi8c40crbi1bg68e5v7au24sbo.apps.googleusercontent.com',
    iosClientId: '741858065565-nr3mk7l8t7asrmh06ljf6iuoe3aj0r67.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialCo2',
  );
}
